//! Orbit subsystem APIs and compatibility exports.

pub mod acp;
pub mod control_plane;
pub mod credentials;
pub mod execution;
pub mod interactive;
pub mod mcp;
pub mod model;
pub mod providers;
pub mod sdk;
pub mod telemetry;
pub mod tools;
pub mod verification;
pub mod workflow;

// Retain established library paths while subsystem namespaces express ownership.
pub use acp::broker as acp_broker;
pub use acp::capabilities as acp_capabilities;
pub use acp::contract as acp_contract;
pub use acp::files as acp_files;
pub use acp::process as acp_process;
pub use acp::runtime as acp_runtime;
pub use acp::terminal as acp_terminal;
pub use acp::wire as acp_wire;
pub use control_plane::api;
pub use control_plane::engine;
pub use control_plane::governance;
pub use control_plane::operations as ops;
pub use control_plane::registry;
pub use control_plane::worker;
pub use credentials::enrollment as credential_enrollment;
pub use credentials::registry as credential_registry;
pub use credentials::secret_backend;
pub use credentials::status_view as credential_status_view;
pub use execution::agent;
pub use execution::coding_agent;
pub use execution::command_agent;
pub use execution::compute;
pub use execution::container;
pub use execution::repository;
pub use execution::workspace;
pub use providers::antigravity::cli_representation as agy_cli_representation;
pub use providers::antigravity::usage_schema as agy_usage_schema;
pub use providers::availability;
pub use providers::codex::bridge as codex_bridge;
pub use providers::codex::enrollment as codex_credential_enrollment;
pub use providers::codex::session as codex_session;
pub use providers::codex::status_probe as codex_status_probe;
pub use providers::scope as provider_scope;
pub use providers::status as provider_status;
pub use telemetry::artifacts;
pub use telemetry::evidence;
pub use telemetry::run_export;
pub use tools::filesystem as fs_tools;
pub use tools::surface as tool_surface;
pub use verification::browser as browser_verification;
pub use verification::integration_environment;
pub use verification::regression as regression_strategy;
pub use workflow::continuation;
pub use workflow::coordinator as workflow_coordinator;
pub(crate) use workflow::role_prompt;
